version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
      - /frontend/node_modules